MAX_HALF_LIFE = 30
USD_MIN_BALANCE = 400
ORDER_SIZE = 250
SCALP_SIZE = 50
CLOSE_ALL_TRADES = False
MARKETS = ["BTCUSDT", "ETHUSDT", "XRPUSDT", "EOSUSDT", "BCHUSDT", "LTCUSDT", "ADAUSDT", "ETCUSDT", "LINKUSDT", "DOGEUSDT", "SOLUSDT", "MATICUSDT", "BNBUSDT", "UNIUSDT", "ICPUSDT", "AAVEUSDT", "XLMUSDT", "ATOMUSDT", "XTZUSDT", "SUSHIUSDT", "AXSUSDT", "THETAUSDT", "AVAXUSDT", "SHIBUSDT", "MANAUSDT", "GALAUSDT", "SANDUSDT", "DYDXUSDT", "CRVUSDT"]
SCALP_MARKETS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BCHUSDT", "XRPUSDT", "LTCUSDT", "ADAUSDT", "LINKUSDT", "DOGEUSDT", "WIFUSDT", "MATICUSDT", "UNIUSDT", "AAVEUSDT", "DYDXUSDT", "CRVUSDT"]
TEST_MARKETS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "TONUSDT", "ADAUSDT", "SHIBUSDT", "AVAXUSDT", "TRXUSDT", "LINKUSDT", "UNIUSDT", "DOTUSDT", "BCHUSDT", "NEARUSDT", "LTCUSDT", "MATICUSDT", "PEPEUSDT", "ICPUSDT", "KASUSDT", "FETUSDT", "ETCUSDT", "APTUSDT", "RNDRUSDT", "HBARUSDT", "FILUSDT", "STXUSDT", "XLMUSDT", "ARBUSDT", "IMXUSDT", "INJUSDT", "WIFUSDT", "SUIUSDT", "GRTUSDT"]