TRADE_SIZE = 200
LONG_RATIO = 2.0
SHORT_RATIO = 1.0
HIGH_WINDOW = 200
MEDIUM_WINDOW = 300
Z_SCORE_HIGH = 1.5
Z_SCORE_MEDIUM = 2.5
MARKETS = ["ETHUSDT", "SOLUSDT", "INJUSDT", "NEARUSDT", "ENSUSDT", "JUPUSDT", "GMXUSDT", "HYPEUSDT", "AAVEUSDT", "UMAUSDT", "BCHUSDT", "LTCUSDT", "LINKUSDT", "LDOUSDT"]